### ISSUE TITLE
Commands don't show up in help

### ISSUE THREAD

**Issue by strugee** [ljcl/hubot-iss#1]
With `hubot-iss` loaded, doing `hubot: help iss` returns nothing when it should obviously return something.

Not sure if this is a Hubot issue or a hubot-iss issue, but there it is. Super cool module, btw :)

**Comment by ljcl** [comment]
Webpack was stripping it out, just had not accounted for that.

I've gotten rid of webpack entirely and made sure that help text comes through okay.

https://www.npmjs.com/package/hubot-iss
